In [1]:
my_str = "python for Data science!!!"

print(my_str.startswith("Python"))
print(my_str.endswith("!"))
print(my_str.find("for"))
print(my_str.count("!"))
print(my_str.capitalize())
print(my_str.title())
print(my_str.upper())
print(my_str.lower())
print(my_str.swapcase())
print(my_str.replace("science", "analysis"))


False
True
7
3
Python for data science!!!
Python For Data Science!!!
PYTHON FOR DATA SCIENCE!!!
python for data science!!!
PYTHON FOR dATA SCIENCE!!!
python for Data analysis!!!


In [2]:
list
age = [19, 21, 20, 19, 21, 17, 30, 36]

age.append(90)
print(age)
brook_age = age.pop()
print(brook_age)
print(age)
age.insert(8, brook_age)
age.remove(brook_age)
print(age.index(21))
age.append(90)
age.append(90)
print(age.count(90))
age.sort()
print(age)
age.reverse()
print(age)

[19, 21, 20, 19, 21, 17, 30, 36, 90]
90
[19, 21, 20, 19, 21, 17, 30, 36]
1
2
[17, 19, 19, 20, 21, 21, 30, 36, 90, 90]
[90, 90, 36, 30, 21, 21, 20, 19, 19, 17]


In [3]:
# as of 2016-12-13
team_name = "金州勇士隊"
wins = 21
losses = 4
win_percentage = 0.84
is_on_winning_streak = True

golden_state_warriors = {
    "team_name": team_name,
    "wins": wins,
    "losses": losses,
    "win_percentage": win_percentage,
    "is_on_winning_streak": is_on_winning_streak
}

print(golden_state_warriors.get("wins"))
print(golden_state_warriors.keys()) # 用 list 把結果轉換
print(golden_state_warriors.values()) # 用 list 把結果轉換

21
dict_keys(['win_percentage', 'is_on_winning_streak', 'losses', 'wins', 'team_name'])
dict_values([0.84, True, 4, 21, '金州勇士隊'])


In [5]:
import numpy as np

print(np.zeros(6)) # 六個元素均為零的 1d array
print(np.arange(11)) # 十一個元素為 0 到 10 的 1d array
print(np.arange(1, 11)) # 十個元素為 1 到 10 的 1d array
print(np.arange(10).astype(np.str)) # 利用 astype() 方法轉換為文字 
print(np.arange(10).reshape(2, 5)) # 利用 reshape() 轉換為矩陣
print(np.arange(10).reshape(5, 2)) # 利用 reshape() 轉換為矩陣
print(np.arange(10).reshape(2, 5).T) # 利用 T 屬性轉置
print(np.random.normal(size = 10)) # 生成 10 組標準常態分配（平均值為 0，標準差為 1 的常態分配）隨機變數
print(np.random.uniform(size = 10)) # 生成 10 組介於 0 與 1 之間均勻分配隨機變數

[ 0.  0.  0.  0.  0.  0.]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[ 1.9882896  -0.36334174 -0.7086713  -0.9335078  -0.05052996  1.07852688
 -0.47714561  1.06139791  0.78778424 -0.50089223]
[ 0.6516116   0.12253864  0.28553744  0.87037859  0.50375719  0.71720537
  0.77473411  0.43240316  0.96400024  0.19467835]


In [11]:

import pandas as pd

name = ["蒙其·D·魯夫", "羅羅亞·索隆", "娜美", "騙人布", "賓什莫克·香吉士", "多尼多尼·喬巴", "妮可·羅賓", "佛朗基", "布魯克"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]

# 建立 dict
straw_hat_dict = {"name": name,
                  "age": age
}

# 刪除觀測值或欄位
straw_hat_df.drop(0, axis = 0)
straw_hat_df.drop(1, axis = 1)

# 選擇觀測值或欄位
straw_hat_df.ix[0, :]
straw_hat_df.ix[:, 0]
straw_hat_df.ix[0, 0]

# 透過布林值篩選
filter = straw_hat_df.age >= 30
straw_hat_df[filter]
filter = straw_hat_df.age < 30
filter_2 = straw_hat_df.name == "蒙其·D·魯夫"
straw_hat_df[filter & filter_2]


ValueError: labels [1] not contained in axis