In [1]:
#list, tuple
# dict
team_name = "金州勇士隊"
wins = 21
losses = 4
win_percentage = 0.84
is_on_winning_streak = True

golden_state_warriors = {
    "team_name": team_name, #"team_name" is key, var team_name assigns value to this key
    "wins": wins,
    "losses": losses,
    "win_percentage": win_percentage,
    "is_on_winning_streak": is_on_winning_streak
}

print(golden_state_warriors["team_name"])
print(golden_state_warriors["wins"])
print(golden_state_warriors["losses"])
print(golden_state_warriors["win_percentage"])
print(golden_state_warriors["is_on_winning_streak"])

金州勇士隊
21
4
0.84
True


In [1]:
# above sample can be view as one row in a table, 
# or 1 record in a dataset
#dict can contains different data type

In [2]:
# elementwise
km_list = [21, 42.195]
km_to_mile = 1.60934
mile_list = km_list * km_to_list
print(mile_list)

NameError: name 'km_to_list' is not defined

In [3]:
# oops, not support elementwise calculation
# Therefore we nned ndarray

In [4]:
import numpy #hey, whats numpy

km_list = [21, 42.195]
km_array = numpy.array(km_list)
print(type(km_array))


<class 'numpy.ndarray'>


In [5]:
km_to_mile = 0.621371192
mile_array = km_array * km_to_mile
print(mile_array)

[ 13.04879503  26.21875745]


In [6]:
# km_array's type is numpy.ndarray 
#numpy is the fundamental package for scientific computing 

In [7]:
import numpy as np # 引入 numpy 套件

km_list = [21, 42.195]
km_array = np.array(km_list)
print(type(km_array))
km_to_mile = 0.621371192
mile_array = km_array * km_to_mile
print(mile_array)

<class 'numpy.ndarray'>
[ 13.04879503  26.21875745]


In [8]:
# ndarray 只能容許一個資料類型
my_np_array = np.array([1, True])
print(my_np_array.dtype)
my_np_array = np.array([1, True, "one"])
print(my_np_array.dtype)

int32
<U11


In [10]:
# 補充, ndarray 可以支援向量運算, elementwise computing
#ndarray 可以建立矩陣
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
print(my_np_array)
print(my_np_array ** 2)
print("---") # 分隔一下

my_2d_array = np.array([[1, 3],
                        [2, 4]])
print(my_2d_array)
print(my_2d_array ** 2)

[1 2 3 4]
[ 1  4  9 16]
---
[[1 3]
 [2 4]]
[[ 1  9]
 [ 4 16]]


In [11]:
# above shows element-wise computing, which py list cannot do

In [13]:
print(type(my_2d_array))

<class 'numpy.ndarray'>


In [14]:
print(type(my_2d_array[0]))
print(my_2d_array[0])

<class 'numpy.ndarray'>
[1 3]


In [1]:
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
print(my_np_array[0])

my_2d_array = np.array([[1, 3],
                        [2, 4]])
print(my_2d_array[1, 1])


1
4


In [2]:
# 矩陣 通常  第一個所引值指列 row, 第二個是欄 column
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
filter = my_np_array < 2
print(my_np_array[filter])

print("---") # 分隔一下

my_2d_array = np.array([[1, 3],
                        [2, 4]])
filter = my_2d_array >=2
print(my_2d_array[filter])

[1]
---
[3 2 4]


In [5]:
# lets try filter2 = 1 == 1
filter2 = 1 == 1
print (my_np_array[filter2])

2


C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  app.launch_new_instance()


In [6]:
# error happened
# lets try filter3 = 1
filter3 = 1
print (my_np_array[filter3])


2


In [7]:
# this is an useful skills to handle your dataset

In [8]:
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
print(my_np_array.size)
print(my_np_array.shape)

print("---") # 分隔一下

my_2d_array = np.array([[1, 3],
                        [2, 4]])
print(my_2d_array.size)
print(my_2d_array.shape)

4
(4,)
---
4
(2, 2)


In [9]:
print(type(my_2d_array))

<class 'numpy.ndarray'>


In [10]:
# size告訴有多少元素, shape 給出 array是 m x n

In [11]:
#lets try
my_2d_array2 = np.array([[1, 3, 6],
                        [2, 4, 8]])

In [12]:
print(my_2d_array2.size)
print(my_2d_array2.shape)

6
(2, 3)


In [13]:
# 2 列 row,  3 欄 column
# 元素型導向,在函數型編程, 跟物件導向編程的差異
# 物件導向是看物件裡什麼方法或屬性來做這件事
# 另一個是要去找一個函數來做

In [1]:
# Pandas dataframe
import pandas as pd # 引用套件並縮寫為 pd

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]

straw_hat_dict = {"name": name,
                  "age": age
}

In [2]:
print(straw_hat_dict["name" = "Monkey D. Luffy"])

SyntaxError: invalid syntax (<ipython-input-2-478fa089464a>, line 1)

In [3]:
print(straw_hat_dict[name = "Monkey D. Luffy"])

SyntaxError: invalid syntax (<ipython-input-3-2b62792331cf>, line 1)

In [4]:
straw_hat_df = pd.DataFrame(straw_hat_dict)
print(type(straw_hat_df))
straw_hat_df

<class 'pandas.core.frame.DataFrame'>


age               name
0   19    Monkey D. Luffy
1   21       Roronoa Zoro
2   20               Nami
3   19              Usopp
4   21     Vinsmoke Sanji
5   17  Tony Tony Chopper
6   30         Nico Robin
7   36             Franky
8   90              Brook

In [8]:
print(straw_hat_dict[2])

KeyError: 2

In [10]:
name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"]
age = [19, 21, 20, 19, 21, 17, 30, 36, 90]
is_male = [True, True, False, True, True, True, False, True, True]

straw_hat_dict = {"name": name,
                  "age": age,
                  "is_male": is_male
}

straw_hat_df = pd.DataFrame(straw_hat_dict)
print(straw_hat_df.dtypes)

age         int64
is_male      bool
name       object
dtype: object


In [11]:
# data frame 可以容納不同變數類型

In [12]:
print(straw_hat_df.ix[0, :]) # 選第一個觀測值
print("---")
print(straw_hat_df.ix[:, "name"]) # 選第一欄
print("---")
print(straw_hat_df.ix[0, "name"]) # 選第一個觀測值的第一欄

age                     19
is_male               True
name       Monkey D. Luffy
Name: 0, dtype: object
---
0      Monkey D. Luffy
1         Roronoa Zoro
2                 Nami
3                Usopp
4       Vinsmoke Sanji
5    Tony Tony Chopper
6           Nico Robin
7               Franky
8                Brook
Name: name, dtype: object
---
Monkey D. Luffy


In [13]:
straw_hat_dict

{'age': [19, 21, 20, 19, 21, 17, 30, 36, 90],
 'is_male': [True, True, False, True, True, True, False, True, True],
 'name': ['Monkey D. Luffy',
  'Roronoa Zoro',
  'Nami',
  'Usopp',
  'Vinsmoke Sanji',
  'Tony Tony Chopper',
  'Nico Robin',
  'Franky',
  'Brook']}

In [14]:
straw_hat_df

age is_male               name
0   19    True    Monkey D. Luffy
1   21    True       Roronoa Zoro
2   20   False               Nami
3   19    True              Usopp
4   21    True     Vinsmoke Sanji
5   17    True  Tony Tony Chopper
6   30   False         Nico Robin
7   36    True             Franky
8   90    True              Brook

In [15]:
straw_hat_df.ix[0, : ]

age                     19
is_male               True
name       Monkey D. Luffy
Name: 0, dtype: object

In [16]:
straw_hat_df.ix[:,"age"]

0    19
1    21
2    20
3    19
4    21
5    17
6    30
7    36
8    90
Name: age, dtype: int64

In [17]:
straw_hat_df.ix["name":"age"]

Empty DataFrame
Columns: [age, is_male, name]
Index: []

In [18]:
straw_hat_df.ix["name":"age":]

Empty DataFrame
Columns: [age, is_male, name]
Index: []

In [19]:
straw_hat_df.ix["name":]

Empty DataFrame
Columns: [age, is_male, name]
Index: []

In [20]:
m=1
n=1
straw_hat_df.ix[m:n]

age is_male          name
1   21    True  Roronoa Zoro

In [21]:
# 用 df_name.ix[m, n] 來選取, 養成使用ix的習慣

In [22]:
straw_hat_df[m,n]

KeyError: (1, 1)

In [23]:
# 一定要加 ix 否則會 error

In [24]:
straw_hat_df.ix[:,"name"]

0      Monkey D. Luffy
1         Roronoa Zoro
2                 Nami
3                Usopp
4       Vinsmoke Sanji
5    Tony Tony Chopper
6           Nico Robin
7               Franky
8                Brook
Name: name, dtype: object

In [25]:
# 用 df_name.ix[m, n] 來選取 或是 df_name.ix[key1, key2] , 養成使用ix的習慣

In [26]:
# lets try filter
filter = straw_hat_df.ix[:, "age"] <= 30
straw_hat_df[filter]

age is_male               name
0   19    True    Monkey D. Luffy
1   21    True       Roronoa Zoro
2   20   False               Nami
3   19    True              Usopp
4   21    True     Vinsmoke Sanji
5   17    True  Tony Tony Chopper
6   30   False         Nico Robin

In [27]:
filter2 = straw_hat_df.ix[:, "is_male"] == False
straw_hat_df[filter2]

age is_male        name
2   20   False        Nami
6   30   False  Nico Robin

In [28]:
filter3 = straw_hat_df.ix[:, "name"] == "Monkey D. Luffy"
straw_hat_df[filter3]

age is_male             name
0   19    True  Monkey D. Luffy

In [29]:
straw_hat_df.shape

(9, 3)

In [30]:
straw_hat_df.describe()

age
count   9.000000
mean   30.333333
std    23.205603
min    17.000000
25%    19.000000
50%    21.000000
75%    30.000000
max    90.000000

In [31]:
straw_hat_df.head(3)

age is_male             name
0   19    True  Monkey D. Luffy
1   21    True     Roronoa Zoro
2   20   False             Nami

In [32]:
straw_hat_df.tail(3)

age is_male        name
6   30   False  Nico Robin
7   36    True      Franky
8   90    True       Brook

In [33]:
straw_hat_df.columns

Index(['age', 'is_male', 'name'], dtype='object')

In [34]:
straw_hat_df.index

RangeIndex(start=0, stop=9, step=1)