In [1]:
#list, tuple
# dict
team_name = "金州勇士隊"
wins = 21
losses = 4
win_percentage = 0.84
is_on_winning_streak = True

golden_state_warriors = {
    "team_name": team_name, #"team_name" is key, var team_name assigns value to this key
    "wins": wins,
    "losses": losses,
    "win_percentage": win_percentage,
    "is_on_winning_streak": is_on_winning_streak
}

print(golden_state_warriors["team_name"])
print(golden_state_warriors["wins"])
print(golden_state_warriors["losses"])
print(golden_state_warriors["win_percentage"])
print(golden_state_warriors["is_on_winning_streak"])

金州勇士隊
21
4
0.84
True


In [1]:
# above sample can be view as one row in a table, 
# or 1 record in a dataset
#dict can contains different data type

In [2]:
# elementwise
km_list = [21, 42.195]
km_to_mile = 1.60934
mile_list = km_list * km_to_list
print(mile_list)

NameError: name 'km_to_list' is not defined

In [3]:
# oops, not support elementwise calculation
# Therefore we nned ndarray

In [4]:
import numpy #hey, whats numpy

km_list = [21, 42.195]
km_array = numpy.array(km_list)
print(type(km_array))


<class 'numpy.ndarray'>


In [5]:
km_to_mile = 0.621371192
mile_array = km_array * km_to_mile
print(mile_array)

[ 13.04879503  26.21875745]


In [6]:
# km_array's type is numpy.ndarray 
#numpy is the fundamental package for scientific computing 

In [7]:
import numpy as np # 引入 numpy 套件

km_list = [21, 42.195]
km_array = np.array(km_list)
print(type(km_array))
km_to_mile = 0.621371192
mile_array = km_array * km_to_mile
print(mile_array)

<class 'numpy.ndarray'>
[ 13.04879503  26.21875745]


In [8]:
# ndarray 只能容許一個資料類型
my_np_array = np.array([1, True])
print(my_np_array.dtype)
my_np_array = np.array([1, True, "one"])
print(my_np_array.dtype)

int32
<U11


In [10]:
# 補充, ndarray 可以支援向量運算, elementwise computing
#ndarray 可以建立矩陣
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
print(my_np_array)
print(my_np_array ** 2)
print("---") # 分隔一下

my_2d_array = np.array([[1, 3],
                        [2, 4]])
print(my_2d_array)
print(my_2d_array ** 2)

[1 2 3 4]
[ 1  4  9 16]
---
[[1 3]
 [2 4]]
[[ 1  9]
 [ 4 16]]


In [11]:
# above shows element-wise computing, which py list cannot do

In [13]:
print(type(my_2d_array))

<class 'numpy.ndarray'>


In [14]:
print(type(my_2d_array[0]))
print(my_2d_array[0])

<class 'numpy.ndarray'>
[1 3]


In [1]:
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
print(my_np_array[0])

my_2d_array = np.array([[1, 3],
                        [2, 4]])
print(my_2d_array[1, 1])


1
4


In [2]:
# 矩陣 通常  第一個所引值指列 row, 第二個是欄 column
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
filter = my_np_array < 2
print(my_np_array[filter])

print("---") # 分隔一下

my_2d_array = np.array([[1, 3],
                        [2, 4]])
filter = my_2d_array >=2
print(my_2d_array[filter])

[1]
---
[3 2 4]


In [5]:
# lets try filter2 = 1 == 1
filter2 = 1 == 1
print (my_np_array[filter2])

2


C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  app.launch_new_instance()


In [6]:
# error happened
# lets try filter3 = 1
filter3 = 1
print (my_np_array[filter3])


2


In [7]:
# this is an useful skills to handle your dataset

In [8]:
import numpy as np

my_np_array = np.array([1, 2, 3, 4])
print(my_np_array.size)
print(my_np_array.shape)

print("---") # 分隔一下

my_2d_array = np.array([[1, 3],
                        [2, 4]])
print(my_2d_array.size)
print(my_2d_array.shape)

4
(4,)
---
4
(2, 2)


In [9]:
print(type(my_2d_array))

<class 'numpy.ndarray'>


In [10]:
# size告訴有多少元素, shape 給出 array是 m x n

In [11]:
#lets try
my_2d_array2 = np.array([[1, 3, 6],
                        [2, 4, 8]])

In [12]:
print(my_2d_array2.size)
print(my_2d_array2.shape)

6
(2, 3)


In [13]:
# 2 列 row,  3 欄 column
# 元素型導向,在函數型編程, 跟物件導向編程的差異
# 物件導向是看物件裡什麼方法或屬性來做這件事
# 另一個是要去找一個函數來做